# Generated by Django 5.2 on 2025-10-10 18:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='operadores/', verbose_name='Logo')),
                ('color_principal', models.CharField(default='#000000', help_text='Color en formato HEX', max_length=7)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('telefono_atencion', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Operador',
                'verbose_name_plural': 'Operadores',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('telefono', models.CharField(db_index=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('zona', models.CharField(blank=True, max_length=100, verbose_name='Zona/Distrito')),
                ('tipo_servicio_interes', models.CharField(blank=True, choices=[('INTERNET', 'Internet Hogar'), ('MOVIL', 'Plan Móvil'), ('TV', 'TV por Cable'), ('TELEFONIA', 'Telefonía Fija'), ('COMBO', 'Paquete Combo')], max_length=20, verbose_name='Tipo de Servicio de Interés')),
                ('presupuesto_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Presupuesto Estimado')),
                ('score', models.PositiveIntegerField(default=0, help_text='Score de calidad del lead', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Score (0-100)')),
                ('clasificacion', models.CharField(choices=[('HOT', '🔥 Hot Lead (Listo para comprar)'), ('WARM', '🌡️ Warm Lead (Interesado)'), ('COLD', '❄️ Cold Lead (Solo preguntando)')], default='COLD', max_length=10, verbose_name='Clasificación')),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo'), ('CONTACTADO', 'Contactado'), ('CALIFICADO', 'Calificado'), ('NEGOCIANDO', 'En Negociación'), ('GANADO', 'Venta Ganada'), ('PERDIDO', 'Venta Perdida'), ('SEGUIMIENTO', 'En Seguimiento')], default='NUEVO', max_length=20, verbose_name='Estado')),
                ('fuente', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('LLAMADA_ENTRANTE', 'Llamada Entrante'), ('LLAMADA_SALIENTE', 'Llamada Saliente'), ('WEB', 'Formulario Web'), ('REFERIDO', 'Referido'), ('REDES_SOCIALES', 'Redes Sociales'), ('OTRO', 'Otro')], default='WHATSAPP', max_length=30, verbose_name='Fuente')),
                ('notas_ia', models.JSONField(blank=True, default=dict, help_text='Análisis automático generado por IA', verbose_name='Análisis de IA')),
                ('intenciones_detectadas', models.JSONField(blank=True, default=list, help_text='Intenciones detectadas en conversaciones', verbose_name='Intenciones Detectadas')),
                ('objeciones', models.JSONField(blank=True, default=list, help_text='Objeciones mencionadas por el lead', verbose_name='Objeciones')),
                ('ultima_interaccion', models.DateTimeField(blank=True, null=True, verbose_name='Última Interacción')),
                ('proxima_accion', models.TextField(blank=True, verbose_name='Próxima Acción Sugerida')),
                ('fecha_proxima_accion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Próxima Acción')),
                ('notas', models.TextField(blank=True, verbose_name='Notas Adicionales')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('agente_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Agente Asignado')),
                ('operador_interes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='callcenter.operador', verbose_name='Operador de Interés')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('LLAMADA', 'Llamada Telefónica'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('WEB_CHAT', 'Chat Web')], max_length=20, verbose_name='Canal')),
                ('tipo', models.CharField(choices=[('ENTRANTE', 'Entrante'), ('SALIENTE', 'Saliente')], max_length=20, verbose_name='Tipo')),
                ('mensaje_cliente', models.TextField(verbose_name='Mensaje del Cliente')),
                ('respuesta_sistema', models.TextField(blank=True, verbose_name='Respuesta del Sistema')),
                ('transcripcion', models.TextField(blank=True, help_text='Transcripción completa de llamada', verbose_name='Transcripción')),
                ('duracion_segundos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración (segundos)')),
                ('sentimiento', models.CharField(choices=[('POSITIVO', '😊 Positivo'), ('NEUTRAL', '😐 Neutral'), ('NEGATIVO', '😞 Negativo')], default='NEUTRAL', max_length=20, verbose_name='Sentimiento')),
                ('fue_atendido_por_ia', models.BooleanField(default=True, verbose_name='Atendido por IA')),
                ('intenciones_detectadas', models.JSONField(blank=True, default=list, verbose_name='Intenciones Detectadas')),
                ('objeciones_detectadas', models.JSONField(blank=True, default=list, verbose_name='Objeciones Detectadas')),
                ('siguiente_accion', models.TextField(blank=True, verbose_name='Siguiente Acción Sugerida')),
                ('audio_url', models.URLField(blank=True, help_text='Para llamadas grabadas', null=True, verbose_name='URL del Audio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('agente_humano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones_atendidas', to=settings.AUTH_USER_MODEL, verbose_name='Agente Humano')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to='callcenter.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LlamadaIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRANTE', 'Entrante'), ('SALIENTE', 'Saliente')], max_length=20, verbose_name='Tipo')),
                ('telefono_destino', models.CharField(max_length=20, verbose_name='Teléfono Destino')),
                ('duracion_segundos', models.PositiveIntegerField(default=0, verbose_name='Duración (segundos)')),
                ('audio_url', models.URLField(blank=True, null=True, verbose_name='URL del Audio')),
                ('transcripcion', models.TextField(blank=True, verbose_name='Transcripción')),
                ('analisis_sentimiento', models.JSONField(blank=True, default=dict, verbose_name='Análisis de Sentimiento')),
                ('palabras_clave_detectadas', models.JSONField(blank=True, default=list, verbose_name='Palabras Clave Detectadas')),
                ('resultado', models.CharField(choices=[('EXITOSA', '✅ Exitosa'), ('BUZON', '📞 Buzón de Voz'), ('NO_CONTESTA', '❌ No Contesta'), ('RECHAZADA', '🚫 Rechazada'), ('NUMERO_INVALIDO', '⚠️ Número Inválido'), ('OCUPADO', '📵 Ocupado')], default='NO_CONTESTA', max_length=20, verbose_name='Resultado')),
                ('siguiente_accion_sugerida', models.TextField(blank=True, verbose_name='Siguiente Acción Sugerida')),
                ('call_sid', models.CharField(blank=True, help_text='ID de la llamada en Twilio', max_length=100, verbose_name='Call SID')),
                ('api_response', models.JSONField(blank=True, default=dict, verbose_name='Respuesta de API')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('conversacion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llamada_detalle', to='callcenter.conversacion', verbose_name='Conversación')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llamadas', to='callcenter.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Llamada IA',
                'verbose_name_plural': 'Llamadas IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INTERNET', 'Internet Hogar'), ('MOVIL', 'Plan Móvil'), ('TV', 'TV por Cable'), ('TELEFONIA', 'Telefonía Fija'), ('COMBO', 'Paquete Combo')], max_length=20, verbose_name='Tipo de Servicio')),
                ('nombre_plan', models.CharField(max_length=200, verbose_name='Nombre del Plan')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('velocidad_mbps', models.PositiveIntegerField(blank=True, help_text='Para planes de Internet', null=True, verbose_name='Velocidad (Mbps)')),
                ('gigas_datos', models.PositiveIntegerField(blank=True, help_text='Para planes móviles', null=True, verbose_name='Gigas de Datos')),
                ('minutos_llamadas', models.PositiveIntegerField(blank=True, help_text='Para planes móviles', null=True, verbose_name='Minutos de Llamadas')),
                ('canales_tv', models.PositiveIntegerField(blank=True, help_text='Para planes de TV', null=True, verbose_name='Canales de TV')),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Mensual')),
                ('precio_instalacion', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio de Instalación')),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Descuento (%)')),
                ('beneficios', models.JSONField(blank=True, default=list, help_text='Lista de beneficios del plan', verbose_name='Beneficios')),
                ('restricciones', models.TextField(blank=True, help_text='Letra pequeña, restricciones del plan', verbose_name='Restricciones')),
                ('zonas_disponibles', models.TextField(blank=True, help_text='Zonas geográficas donde está disponible', verbose_name='Zonas Disponibles')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_destacado', models.BooleanField(default=False, verbose_name='Plan Destacado')),
                ('stock_disponible', models.PositiveIntegerField(default=999, verbose_name='Stock Disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='callcenter.operador', verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-is_destacado', 'operador', 'tipo', 'precio_mensual'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='producto_interes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='callcenter.producto', verbose_name='Producto de Interés'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fue_venta_ia', models.BooleanField(default=False, verbose_name='Venta Cerrada por IA')),
                ('precio_final', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Final')),
                ('descuento_aplicado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento Aplicado')),
                ('comision_agente', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Comisión del Agente')),
                ('fecha_venta', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Venta')),
                ('fecha_instalacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Instalación')),
                ('direccion_instalacion', models.TextField(verbose_name='Dirección de Instalación')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Instalación'), ('INSTALADO', 'Instalado'), ('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Agente')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='callcenter.lead', verbose_name='Lead/Cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='callcenter.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['lead', '-created_at'], name='callcenter__lead_id_81921a_idx'),
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['canal', 'tipo'], name='callcenter__canal_7fbc26_idx'),
        ),
        migrations.AddIndex(
            model_name='llamadaia',
            index=models.Index(fields=['lead', '-created_at'], name='callcenter__lead_id_a1967c_idx'),
        ),
        migrations.AddIndex(
            model_name='llamadaia',
            index=models.Index(fields=['resultado'], name='callcenter__resulta_80ffa5_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['operador', 'tipo'], name='callcenter__operado_24e1d4_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['is_active', 'is_destacado'], name='callcenter__is_acti_e0aac3_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['telefono'], name='callcenter__telefon_36dfb6_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['clasificacion', 'estado'], name='callcenter__clasifi_2e1b7c_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['agente_asignado', 'estado'], name='callcenter__agente__2e1193_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['-score'], name='callcenter__score_efedf2_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['lead', 'estado'], name='callcenter__lead_id_561550_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['agente', '-created_at'], name='callcenter__agente__5c4838_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['-fecha_venta'], name='callcenter__fecha_v_2959bb_idx'),
        ),
    ]
