# Generated by Django 4.2.7 on 2025-09-08 20:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('icono', models.CharField(blank=True, help_text='Clase de ícono de Bootstrap Icons (ej: netflix, spotify, etc.)', max_length=50, verbose_name='Ícono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Categoría de servicio',
                'verbose_name_plural': 'Categorías de servicios',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono del cliente con código de país', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe tener el formato: '+999999999'. Hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas adicionales')),
                ('is_active', models.BooleanField(default=True, verbose_name='Cliente activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellidos', 'nombres'],
                'permissions': [('can_manage_clients', 'Puede gestionar clientes')],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre interno')),
                ('nombre_mostrar', models.CharField(max_length=100, verbose_name='Nombre para mostrar')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio base')),
                ('tipo_suscripcion', models.CharField(choices=[('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('semiannual', 'Semestral'), ('annual', 'Anual')], default='monthly', max_length=20, verbose_name='Tipo de suscripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('icono', models.CharField(blank=True, help_text='Clase de ícono de Bootstrap Icons (ej: netflix, spotify, etc.)', max_length=50, verbose_name='Ícono')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='servicios/', verbose_name='Imagen destacada')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='subscriptions.categoriaservicio', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['categoria__nombre', 'nombre_mostrar'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio pagado')),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia bancaria'), ('card', 'Tarjeta de crédito/débito'), ('other', 'Otro método')], default='cash', max_length=20, verbose_name='Método de pago')),
                ('payment_status', models.CharField(choices=[('pending', 'Pendiente de pago'), ('paid', 'Pagado'), ('cancelled', 'Cancelado'), ('expired', 'Expirado'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado del pago')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia de pago')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de expiración')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cancelación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('notes', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('stripe_customer_id', models.CharField(blank=True, help_text='ID del cliente en Stripe', max_length=100, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, help_text='ID de la suscripción en Stripe', max_length=100, null=True)),
                ('stripe_payment_intent', models.CharField(blank=True, help_text='ID del intento de pago en Stripe', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions.cliente', verbose_name='Cliente')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.service', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ['-created_at'],
                'permissions': [('can_manage_subscriptions', 'Puede gestionar suscripciones')],
            },
        ),
    ]
