# Generated by Django 4.2.7 on 2025-09-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='calidad',
            field=models.CharField(blank=True, help_text='Ej: 4K, 1080p, 720p', max_length=50, null=True, verbose_name='Calidad de video'),
        ),
        migrations.AddField(
            model_name='service',
            name='fecha_lanzamiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de lanzamiento'),
        ),
        migrations.AddField(
            model_name='service',
            name='idiomas',
            field=models.TextField(blank=True, help_text='Separe los idiomas con comas', null=True, verbose_name='Idiomas disponibles'),
        ),
        migrations.AddField(
            model_name='service',
            name='max_dispositivos',
            field=models.PositiveIntegerField(default=1, help_text='Número máximo de dispositivos permitidos para este servicio', verbose_name='Máximo de dispositivos'),
        ),
        migrations.AddField(
            model_name='service',
            name='pais_origen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='País de origen'),
        ),
        migrations.AddField(
            model_name='service',
            name='sitio_web',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio web oficial'),
        ),
    ]
