# Generated by Django 4.2.7 on 2025-09-15 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0003_service_calidad_service_fecha_lanzamiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('expiration_warning', 'Aviso de vencimiento'), ('renewal_confirmation', 'Confirmación de renovación'), ('payment_reminder', 'Recordatorio de pago')], max_length=50, verbose_name='Tipo de notificación')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('failed', 'Fallido'), ('delivered', 'Entregado'), ('read', 'Leído')], default='pending', max_length=20, verbose_name='Estado')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Número de teléfono')),
                ('message_content', models.TextField(verbose_name='Contenido del mensaje')),
                ('days_notice', models.IntegerField(blank=True, help_text='Días antes del vencimiento (solo para avisos de vencimiento)', null=True, verbose_name='Días de aviso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('api_response', models.JSONField(blank=True, null=True, verbose_name='Respuesta de la API')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensaje de error')),
                ('retry_count', models.IntegerField(default=0, verbose_name='Intentos de reenvío')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='subscriptions.subscription', verbose_name='Suscripción')),
            ],
            options={
                'verbose_name': 'Registro de Notificación',
                'verbose_name_plural': 'Registros de Notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subscription', 'notification_type'], name='subscriptio_subscri_546a83_idx'), models.Index(fields=['status', 'created_at'], name='subscriptio_status_69c366_idx'), models.Index(fields=['phone_number', 'sent_at'], name='subscriptio_phone_n_47778d_idx')],
            },
        ),
    ]
